### ISSUE TITLE
Json with OneWire

### ISSUE THREAD

**Issue by gmbeas** [Rinsen/WebServer#1]
Hello, I use the OneWire sensor, and after 3 attempts, returns me error

Internal server error

Exception
Message:
Exception was thrown: System.Exception
Stack Trace:
Microsoft.SPOT.Hardware.Port::.ctor
Microsoft.SPOT.Hardware.OutputPort::.ctor
Temperatura.OneWireTemperatureSensorController::.ctor
Temperatura.Temp::ReadTemperature
DemoWeb.TemperaturaController::Index
System.Reflection.MethodBase::Invoke
Rinsen.WebServer.HttpApplicationHandler::Execute
Rinsen.WebServer.RequestResponseHandler::CreateResponse
Rinsen.WebServer.RequestResponseHandler::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessRequest
Rinsen.WebServer.SocketListener+<>c__DisplayClass1::<ProcessClientRequest>b__0

it is due?
very good project, Greetings

**Comment by Rinsen** [comment]
Hi!

I hade had similar problems and they have been related to disposing hardware resourses. One solution for this problem is to reuse the resource handle between sessions as i do in blink example. But you should use a lock for thread safety when you access the OneWire interface.

Im really glad that you like it!

Sincerely,
Fredrik Rinsen

--- Originalmeddelande ---

Från: "Gonzalo Martinez" notifications@github.com
Skickat: 22 december 2014 02:34
Till: "Rinsen/WebServer" WebServer@noreply.github.com
Ämne: [WebServer] Json with OneWire (#1)

Hello, I use the OneWire sensor, and after 3 attempts, returns me error

Internal server error

Exception
Message:
Exception was thrown: System.Exception
Stack Trace:
Microsoft.SPOT.Hardware.Port::.ctor
Microsoft.SPOT.Hardware.OutputPort::.ctor
Temperatura.OneWireTemperatureSensorController::.ctor
Temperatura.Temp::ReadTemperature
DemoWeb.TemperaturaController::Index
System.Reflection.MethodBase::Invoke
Rinsen.WebServer.HttpApplicationHandler::Execute
Rinsen.WebServer.RequestResponseHandler::CreateResponse
Rinsen.WebServer.RequestResponseHandler::ProcessRequest
Rinsen.WebServer.SocketListener::ProcessRequest
Rinsen.WebServer.SocketListener+<>c__DisplayClass1::<ProcessClientRequest>b__0

it is due?
very good project, Greetings

---

Reply to this email directly or view it on GitHub:
https://github.com/Rinsen/WebServer/issues/1
